spring:
  application:
    name: sifap
  datasource:
    url: ${SIFAP_DB_URL:jdbc:postgresql://localhost:5432/sifap}
    username: ${SIFAP_DB_USER:sifap_app}
    password: ${SIFAP_DB_PASSWORD:}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 500
        order_inserts: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${SIFAP_PORT:8080}

logging:
  level:
    root: INFO
